### ISSUE TITLE
Allow to change client timeout in config

### ISSUE THREAD

**Issue by alcalyn** [sensiolabs/SensioBuzzBundle#23]
I can't change timeout value in config, I added in config.yml:

``` yml
sensio_buzz:
    client_timeout: 10
```

But default value is still considered.

This configuration step should be in readme.md

**Comment by alcalyn** [comment]
In fact, the value is considered, but using Curl, it seems that it is not passed to Client

**Comment by gnutix** [comment]
Setting the "verify_peers" => false would be a nice option as well for Curl.

**Comment by alcalyn** [comment]
It was a time ago, I'm not using it anymore
